export const actionTypes = {
  CREATE_USER: "CREATE_USER",
  SET_USERS: "SET_USERS",
  SET_SELECTED_USER: "SET_SELECTED_USER",
  SET_FETCH_USER: "SET_FETCH_USER",
  SET_UPDATE_USER: "SET_UPDATE_USER",
  REMOVE_SELECTED_USER: "REMOVE_SELECTED_USER",

  CREATE_BOOK: "CREATE_BOOK",
  SET_BOOKS: "SET_BOOKS",
  SET_SELECTED_BOOK: "SET_SELECTED_BOOK",
  SET_FETCH_BOOK: "SET_FETCH_BOOK",
  SET_UPDATE_BOOK: "SET_UPDATE_BOOK",
  REMOVE_SELECTED_BOOK: "REMOVE_SELECTED_BOOK",

  SET_UI_SELECTOR: "SET_UI_SELECTOR",
}
